force-app/main/default/objects/EM_Expense__c/EM_Expense__c.object-meta.xml
<CustomObject>
    <description>Expense custom object</description>
    <label>EM_Expense</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>EM_Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Expense__c/fields/EM_Reimbursement_Status__c.field-meta.xml
<CustomField>
    <fullName>EM_Reimbursement_Status__c</fullName>
    <label>Reimbursement status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reimbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Report__c.field-meta.xml
<CustomField>
    <fullName>EM_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report</label>
    <referenceTo>EM_Report__c</referenceTo>
    <relationshipName>EM_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/EM_Report__c.object-meta.xml
<CustomObject>
    <label>EM_Report</label>
    <nameField>
        <displayFormat>REP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Report__c/fields/EM_Expense__c.field-meta.xml
<CustomField>
    <fullName>EM_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EM_Expense</label>
    <referenceTo>EM_Expense__c</referenceTo>
    <relationshipLabel>EM_Reports</relationshipLabel>
    <relationshipName>EM_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Deprecated/EMExpenseController.cls
public with sharing class EMExpenseController {
    
    @AuraEnabled(cacheable=true)
    public static List<ExpenseWrapper> getExpenses() {
        List<EM_Expense__c> expensesList = [SELECT Name, EM_Reimbursement_Status__c, EM_Report__r.Name FROM EM_Expense__c WITH SECURITY_ENFORCED];

        List<ExpenseWrapper> expenses = new List<ExpenseWrapper>();
        Id reportId;
        String reportName;
        Id expenseId;
        String expenseName;
        String expenseStatus;
        for (EM_Expense__c exp : expensesList) {
            reportId = exp.EM_Report__r.Id;
            reportName = exp.EM_Report__r.Name;
            expenseId = exp.Id;
            expenseName = exp.Name;
            expenseStatus = exp.EM_Reimbursement_Status__c;
            ExpenseWrapper expense = new ExpenseWrapper(reportId, reportName, expenseId, expenseName, expenseStatus);
            expenses.add(expense);
        }
        return expenses;
    }



    public class ExpenseWrapper {
        @AuraEnabled
        public Id reportId { get; set; }
        @AuraEnabled
        public String reportName { get; set; }
    	@AuraEnabled
    	public Id expenseId { get; set; }
    	@AuraEnabled
    	public String expenseName { get; set; }
    	@AuraEnabled
    	public String expenseStatus { get; set; }
    	@AuraEnabled
    	public String expenseLabel { get; set; }
    	@AuraEnabled
    	public Decimal transactionAmount { get; set; }
    	@AuraEnabled
    	public Decimal reimbursementAmount { get; set; }
    	@AuraEnabled
    	public String expenseCurrency { get; set; }
    	@AuraEnabled
    	public Date purchaseDate { get; set; }
    	@AuraEnabled
    	public String reimbursementBy { get; set; }
    	public ExpenseWrapper(Id id, String name, String status, String expenseLabel, Decimal transactionAmount, Decimal reimbursementAmount, String expenseCurrency, Date purchaseDate, String reimbursementBy) {
    		this.expenseId = id;
    		this.expenseName = name;
    		this.expenseStatus = status;
    		this.expenseLabel = expenseLabel;
    		this.transactionAmount = transactionAmount;
    		this.reimbursementAmount = reimbursementAmount;
    		this.expenseCurrency = expenseCurrency;
    		this.purchaseDate = purchaseDate;
    		this.reimbursementBy = reimbursementBy;
    	}
        public ExpenseWrapper(Id reportId, String reportName, Id expId, String name, String status) {
            this.reportId = reportId;
            this.reportName = reportName;
            this.expenseId = expId;
            this.expenseName = name;
            this.expenseStatus = status;
        }
    }
}