force-app/main/default/objects/EM_Expense__c/EM_Expense__c.object-meta.xml
<CustomObject>
    <description>Expense custom object</description>
    <label>EM_Expense</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>EM_Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Expense__c/fields/EM_Reimbursement_Status__c.field-meta.xml
<CustomField>
    <fullName>EM_Reimbursement_Status__c</fullName>
    <label>Reimbursement status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reimbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Report__c.field-meta.xml
<CustomField>
    <fullName>EM_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report</label>
    <referenceTo>EM_Report__c</referenceTo>
    <relationshipName>EM_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/EM_Report__c.object-meta.xml
<CustomObject>
    <label>EM_Report</label>
    <nameField>
        <displayFormat>REP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Report__c/fields/EM_Expense__c.field-meta.xml
<CustomField>
    <fullName>EM_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EM_Expense</label>
    <referenceTo>EM_Expense__c</referenceTo>
    <relationshipLabel>EM_Reports</relationshipLabel>
    <relationshipName>EM_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EMReportController.cls
public with sharing class EMReportController {
	// @AuraEnabled(cacheable=true)
	// public static List<ReportsListWrapper> gerReports() {
		
	// 	List<EM_Report__c> reportList = [
	// 		SELECT Name, (SELECT Name, EM_Reimbursement_Status__c FROM EM_Expenses__r)
	// 		FROM EM_Report__c
	// 		WITH SECURITY_ENFORCED
	// 	];

    //     List<ReportsListWrapper> reportsWrapperList = new List<ReportsListWrapper>();
 
    //         for(EM_Report__c rep : reportList){            
    //             String expenseName;
    //             String expenseStatus;
    //             String reportName = rep.Name;

    //         for(EM_Expense__c exp : rep.EM_Expenses__r){
    //             expenseName = exp.Name;
    //             expenseStatus = exp.EM_Reimbursement_Status__c;
    //         }
        

    //         ReportsListWrapper allRep = new ReportsListWrapper(reportName, expenseName, expenseStatus);
    //         reportsWrapperList.add(allRep);
    //     }
        
    //     return reportsWrapperList;
	// }

    @AuraEnabled(cacheable=true)
	public static List<ReportsListWrapper> gerReports() {
		
		List<EM_Expense__c> expensesList = [
			SELECT Name, EM_Reimbursement_Status__c, EM_Report__r.Name
			FROM EM_Expense__c
			WITH SECURITY_ENFORCED
		];

        List<ReportsListWrapper> expensesWrapperList = new List<ReportsListWrapper>();
 
            for(EM_Expense__c expense : expensesList){            
                String expenseName = expense.Name;
                String expenseStatus = expense.EM_Reimbursement_Status__c;
                String reportName = expense.EM_Report__r.Name;
        

            ReportsListWrapper allRep = new ReportsListWrapper(reportName, expenseName, expenseStatus);
            expensesWrapperList.add(allRep);
        }
        
        return expensesWrapperList;
	}

	class ReportsListWrapper {
		@AuraEnabled
		public String reportName { get; set; }
		@AuraEnabled
		public String expenseName { get; set; }
		@AuraEnabled
		public String expenseStatus { get; set; }

        ReportsListWrapper(String repName, String expName, String expStatus){
            reportName = repName;
            expenseName = expName;
            expenseStatus = expStatus;
        }
	}
}