force-app/main/default/objects/EM_Expense__c/EM_Expense__c.object-meta.xml
<CustomObject>
    <description>Expense custom object</description>
    <label>EM_Expense</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>EM_Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Expense__c/fields/EM_Reimbursement_Status__c.field-meta.xml
<CustomField>
    <fullName>EM_Reimbursement_Status__c</fullName>
    <label>Reimbursement status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reimbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Report__c.field-meta.xml
<CustomField>
    <fullName>EM_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report</label>
    <referenceTo>EM_Report__c</referenceTo>
    <relationshipName>EM_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/EM_Report__c.object-meta.xml
<CustomObject>
    <label>EM_Report</label>
    <nameField>
        <displayFormat>REP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Report__c/fields/EM_Expense__c.field-meta.xml
<CustomField>
    <fullName>EM_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EM_Expense</label>
    <referenceTo>EM_Expense__c</referenceTo>
    <relationshipLabel>EM_Reports</relationshipLabel>
    <relationshipName>EM_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <color>#33FF33</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <color>#FFCC33</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Reimbursed</fullName>
                <color>#009900</color>
                <label>Reimbursed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Report/EMReportController.cls
public with sharing class EMReportController {

	@AuraEnabled(cacheable=true)
	public static List<ReportWrapper> getReport() {
		List<EM_Report__c> reportsData = [
			SELECT Id, Name, Status__c, (SELECT Id, Name, EM_Reimbursement_Status__c FROM EM_Expenses__r)
			FROM EM_Report__c
			WITH SECURITY_ENFORCED
		];

		List<ReportWrapper> reports = new List<ReportWrapper>();

		for (EM_Report__c rep : reportsData) {
			List<ExpenseWrapper> expenses = new List<ExpenseWrapper>();

			for (EM_Expense__c exp : rep.EM_Expenses__r) {
				ExpenseWrapper expense = new ExpenseWrapper(exp.id, exp.Name, exp.EM_Reimbursement_Status__c);
				expenses.add(expense);
			}

			ReportWrapper report = new ReportWrapper(rep.id, rep.Name, rep.Status__c, expenses);
			reports.add(report);
		}
		return reports;
	}

	class ReportWrapper {
		@AuraEnabled
		public Id id { get; set; }
		@AuraEnabled
		public String name { get; set; }
		@AuraEnabled
		public String status { get; set; }
		@AuraEnabled
		public List<ExpenseWrapper> expenses { get; set; }
		ReportWrapper(Id id, String name, String status, List<ExpenseWrapper> expenses) {
			this.id = id;
			this.name = name;
			this.status = status;
			this.expenses = expenses;
		}
	}

	class ExpenseWrapper {
		@AuraEnabled
		public Id expenseId { get; set; }
		@AuraEnabled
		public String expenseName { get; set; }
		@AuraEnabled
		public String expenseStatus { get; set; }
		ExpenseWrapper(Id id, String name, String status) {
			this.expenseId = id;
			this.expenseName = name;
			this.expenseStatus = status;
		}
	}
}