force-app/main/default/objects/EM_Expense__c/EM_Expense__c.object-meta.xml
<CustomObject>
    <description>Expense custom object</description>
    <label>EM_Expense</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>EM_Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Expense__c/fields/EM_Currency__c.field-meta.xml
<CustomField>
    <fullName>EM_Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KZT</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>RUB</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>UAH</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Expense_Label__c.field-meta.xml
<CustomField>
    <fullName>EM_Expense_Label__c</fullName>
    <label>Expense Label</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>EM_Purchase_Date__c</fullName>
    <label>Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Reimbursement_Amount__c.field-meta.xml
<CustomField>
    <fullName>EM_Reimbursement_Amount__c</fullName>
    <label>Reimbursement Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Reimbursement_By__c.field-meta.xml
<CustomField>
    <fullName>EM_Reimbursement_By__c</fullName>
    <label>Reimbursement By</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Reimbursement_Status__c.field-meta.xml
<CustomField>
    <fullName>EM_Reimbursement_Status__c</fullName>
    <label>Reimbursement status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reimbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Report__c.field-meta.xml
<CustomField>
    <fullName>EM_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report</label>
    <referenceTo>EM_Report__c</referenceTo>
    <relationshipName>EM_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>EM_Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>9</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/EM_Report__c.object-meta.xml
<CustomObject>
    <label>EM_Report</label>
    <nameField>
        <displayFormat>REP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Report__c/fields/EM_Expense__c.field-meta.xml
<CustomField>
    <fullName>EM_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EM_Expense</label>
    <referenceTo>EM_Expense__c</referenceTo>
    <relationshipLabel>EM_Reports</relationshipLabel>
    <relationshipName>EM_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/fields/EM_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>EM_Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <color>#33FF33</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <color>#FFCC33</color>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Reimbursed</fullName>
                <color>#009900</color>
                <label>Reimbursed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Report/EM_ReportModel.cls
public with sharing class EM_ReportModel {
    public static List<EM_ReportEntity.ReportWrapper> getReport() {
        List<EM_Report__c> reportsData = [SELECT Id, Name, Status__c, EM_Total_Amount__c, 
											(SELECT Id, Name, EM_Expense_Label__c, EM_Transaction_Amount__c, EM_Reimbursement_Amount__c, EM_Currency__c, EM_Reimbursement_Status__c, EM_Purchase_Date__c, EM_Reimbursement_By__c FROM EM_Expenses__r) 
											FROM EM_Report__c WITH SECURITY_ENFORCED];
        List<EM_ReportEntity.ReportWrapper> reports = new List<EM_ReportEntity.ReportWrapper>();
        for (EM_Report__c rep : reportsData) {
            List<EM_ExpenseEntity.ExpenseWrapper> expenses = new List<EM_ExpenseEntity.ExpenseWrapper>();
            for (EM_Expense__c exp : rep.EM_Expenses__r) {
				Id id = exp.id;
				String name = exp.Name;
				String status = exp.EM_Reimbursement_Status__c;
				String expLbl = exp.EM_Expense_Label__c;
				Decimal trnsAm = exp.EM_Transaction_Amount__c;
				Decimal reimAm = exp.EM_Reimbursement_Amount__c;
				String exCur = exp.EM_Currency__c;
				Date purDt = exp.EM_Purchase_Date__c;
				String reimBy = exp.EM_Reimbursement_By__c;
                EM_ExpenseEntity.ExpenseWrapper expense = new EM_ExpenseEntity.ExpenseWrapper(id, name, status, expLbl, trnsAm, reimAm, exCur, purDt, reimBy);
                expenses.add(expense);
			}
			Id id = rep.id;
			String name = rep.Name;
			String status = rep.Status__c;
			Decimal total = rep.EM_Total_Amount__c;
            EM_ReportEntity.ReportWrapper report = new EM_ReportEntity.ReportWrapper(id, name, status, total, expenses);
            reports.add(report);
        }
        return reports;
    }

	public static void getReportsTotalAmount() {
        List<EM_Report__c> lstRep = [SELECT Id, Name, EM_Total_Amount__c, 
                                        (SELECT id, EM_Transaction_Amount__c FROM EM_Expenses__r) 
                                    FROM EM_Report__c WITH SECURITY_ENFORCED];
        EM_ReportService.recalculateReportsTotalAmount(lstRep);
    }
}