force-app/main/default/objects/EM_Expense__c/EM_Expense__c.object-meta.xml
<CustomObject>
    <description>Expense custom object</description>
    <label>EM_Expense</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>EM_Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Expense__c/fields/EM_Report__c.field-meta.xml
<CustomField>
    <fullName>EM_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report</label>
    <referenceTo>EM_Report__c</referenceTo>
    <relationshipName>EM_Expenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Expense__c/fields/EM_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>EM_Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>9</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/EM_Report__c.object-meta.xml
<CustomObject>
    <label>EM_Report</label>
    <nameField>
        <displayFormat>REP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EM_Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EM_Report__c/fields/EM_Expense__c.field-meta.xml
<CustomField>
    <fullName>EM_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EM_Expense</label>
    <referenceTo>EM_Expense__c</referenceTo>
    <relationshipLabel>EM_Reports</relationshipLabel>
    <relationshipName>EM_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EM_Report__c/fields/EM_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>EM_Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Report/EM_ReportService.cls
public with sharing class EM_ReportService {
    
    public static void recalculateReportsTotalAmount(List<EM_Report__c> listReports) {
        Map<Id, List<Decimal>> expensesAmoutn = new Map<Id, List<Decimal>>();

        for (EM_Report__c rep : listReports) {
            List<Decimal> expsAmount = new List<Decimal>();
            Decimal totalAmount = 0.00;
            for (EM_Expense__c exp : rep.EM_Expenses__r) {
                expsAmount.add(exp.EM_Transaction_Amount__c);
            }
            System.debug('expsAmount: ' + expsAmount);
            for (Integer i = 0; i < expsAmount.size(); i++) {
                totalAmount = totalAmount + expsAmount[i];
            }

            expensesAmoutn.put(rep.id, expsAmount);

            rep.EM_Total_Amount__c = totalAmount;
        }
        update listReports;
    }
}